### ISSUE TITLE
How to run? 

### ISSUE THREAD

**Issue by mei-chen** [PSPDFKit-labs/pdfkit-invoice#7]
Where's the entry point to run it to generate the pdf? 
(I'm new to node.js)

**Comment by johan-github** [comment]
I succeeded to generate a PDF by:

1) Adding start-script in the package.json file:
   "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js"
  },

2) Wrote: "npm i" in terminal to install all necessary dependencies. NO quote marks!

3) in terminal, write "npm start". NO quote marks!

This will generate a PDF-file and be put in the project. Open it as a regular PDF-file, looking at it in Visual Studio Code will not be satisfactory.

**Comment by johan-github** [comment]
> I succeeded to generate a PDF by:
> 
> 1. Adding start-script in the package.json file:
>    "scripts": {
>    "test": "echo "Error: no test specified" && exit 1",
>    "start": "node index.js"
>    },
> 2. Wrote: "npm i" in terminal to install all necessary dependencies. NO quote marks!
> 3. in terminal, write "npm start". NO quote marks!
> 
> This will generate a PDF-file and be put in the project. Open it as a regular PDF-file, looking at it in Visual Studio Code will not be satisfactory.
